### ISSUE TITLE
how to run the game

### ISSUE THREAD

**Issue by Frozoto1** [BobMak/SpaceShooter#1]
When I run the game by `python MainLoop.py`,I got the error  "SyntaxError: name 't' is used prior to global declaration"

**Comment by BobMak** [comment]
Thanks!
You need to start `python Main.py`

**Comment by Frozoto1** [comment]
Thanks!
I also get an error when I run by "python Main.py".
The error log is blow:

> Traceback (most recent call last):
  File ".\Main.py", line 8, in <module>
    from Menus import main_menu, player_set
  File "E:\Python_game\SpaceShooter\Menus.py", line 40
    global t
    ^
SyntaxError: name 't' is used prior to global declaration

My Python is Python 3.6.1.
